config/routes.rb
Pakar::Application.routes.draw do
  get "index/index"
  devise_for :users
  post "periksa/create"
  post "periksa/proses"
  get "periksa/index"
  get "periksa/cek"
  get "periksa/hasil"
  get 'periksa' => 'periksa#index'
  get "penyakits/jsonp"
  get "index/kerusakan"
  get "kliens/jsonp"
  get "gejalas/jsonp"

  resources :kliens
  resources :penyakits
  root "index#index"

get '/penyakits/:id/gejala', to: 'penyakits#gejala', as: 'gejala_penyakit'
post '/penyakits/:id/gejalaproses', to: 'penyakits#gejalaproses'

  resources :gejalas

  

end

app/models/penyakit.rb
class Penyakit
  include Mongoid::Document
  field :nama, type: String
  field :deskripsi, type: String
  field :solusi, type: String

  has_and_belongs_to_many  :gejalas
  has_one :klien
end

app/controllers/admin/penyakits_controller.rb
class Admin::PenyakitsController < ApplicationController
  before_action :set_penyakit, only: [:show, :edit, :update, :destroy, :gejala, :gejalaproses]

  # GET /penyakits
  # GET /penyakits.json
  def index

    @penyakits = Penyakit.all
  end

  # GET /penyakits/1
  # GET /penyakits/1.json
  def show

  end

  def gejala
     ar=Array.new
     @penyakit.gejalas.each do | data | 
       ar.push(data._id)
      end 
  @ar=ar
    @gejala=Gejala.order_by()

    
  end

  def gejalaproses
    data=params[:cekgejala]
    @penyakit.gejalas = []
    if data!=nil
    data.each do | datag |
      @penyakit.gejalas << Gejala.find(datag)
    end
  end
    @data=@penyakit.inspect
    redirect_to @penyakit, notice: 'Penyakit was successfully editted.'

  end

  # GET /penyakits/new
  def new
    @penyakit = Penyakit.new
  end

  # GET /penyakits/1/edit
  def edit
  end

  # POST /penyakits
  # POST /penyakits.json
  def create
    @penyakit = Penyakit.new(penyakit_params)

    respond_to do |format|
      if @penyakit.save
        format.html { redirect_to @penyakit, notice: 'Penyakit was successfully created.' }
        format.json { render action: 'show', status: :created, location: @penyakit }
      else
        format.html { render action: 'new' }
        format.json { render json: @penyakit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /penyakits/1
  # PATCH/PUT /penyakits/1.json
  def update
    respond_to do |format|
      if @penyakit.update(penyakit_params)
        format.html { redirect_to @penyakit, notice: 'Penyakit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @penyakit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /penyakits/1
  # DELETE /penyakits/1.json
  def destroy
    @penyakit.destroy
    respond_to do |format|
      format.html { redirect_to penyakits_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_penyakit
      @penyakit = Penyakit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def penyakit_params
      params.require(:penyakit).permit(:nama, :deskripsi, :solusi)
    end
end

app/controllers/penyakits_controller.rb
class PenyakitsController < ApplicationController
  before_action :set_penyakit, only: [:show, :edit, :update, :destroy, :gejala, :gejalaproses]
  before_action :ceklogin
  layout "admin"
  # GET /penyakits
  # GET /penyakits.json
  def index

    @penyakits = Penyakit.all
    ar=[]
    i=0

    @penyakits.each do | datap |
      ar[i]=[]
      datap.gejalas.each do | datag |
        ar[i].push(datag._id.to_s)
      end
      ar[i].sort
      i+=1
    end

    d=[]
    ar.detect{ |e| (ar.count(e) > 1)? d.push(e) : nil ; }

    if d.count >0
      ar = []
      er=[]
      g=Gejala.find(d)
      g.each do | dag |
        ar.push(dag) 
      end
      for i in 0..ar.count-1
        if i!=0
        er=er & ar[i].penyakits
      else
        er = ar[i].penyakits
      end
      end
      @er=er

    end
  end

  # GET /penyakits/1
  # GET /penyakits/1.json
  def show

  end

  def jsonp
    p=params[:idpenyakit]
    if p=='' or p==nil
      datap = Penyakit.all.to_json

      render :json => datap, :callback => params[:callback]
    else

      datag=Gejala.all.to_a
      datag.each do | data |
        data.penyakits.each do | asd |
          if asd._id.to_s==p
            data["penyakit"]="checked"
          end
        end
      end

      render :json => datag.as_json, :callback => params[:callback]

    end
  end

  def gejala
   ar=Array.new
   @penyakit.gejalas.each do | data | 
     ar.push(data._id)
   end 
   @ar=ar
   @namapenyakit=@penyakit.nama
   @gejala=Gejala.order_by()




 end

 def gejalaproses
  data=params[:cekgejala]
  @penyakit.gejalas = []

  if data!=nil

    data.each do | datag |
      @penyakit.gejalas << Gejala.find(datag)
    end
  end
  @data=@penyakit.inspect
  redirect_to @penyakit, notice: 'Penyakit was successfully editted.'

end

  # GET /penyakits/new
  def new
    @penyakit = Penyakit.new
  end

  # GET /penyakits/1/edit
  def edit
  end

  # POST /penyakits
  # POST /penyakits.json
  def create
    @penyakit = Penyakit.new(penyakit_params)

    respond_to do |format|
      if @penyakit.save
        format.html { redirect_to @penyakit, notice: 'Penyakit was successfully created.' }
        format.json { render action: 'show', status: :created, location: @penyakit }
      else
        format.html { render action: 'new' }
        format.json { render json: @penyakit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /penyakits/1
  # PATCH/PUT /penyakits/1.json
  def update
    respond_to do |format|
      if @penyakit.update(penyakit_params)
        format.html { redirect_to @penyakit, notice: 'Penyakit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @penyakit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /penyakits/1
  # DELETE /penyakits/1.json
  def destroy
    @penyakit.destroy
    respond_to do |format|
      format.html { redirect_to penyakits_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_penyakit
      @penyakit = Penyakit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def penyakit_params
      params.require(:penyakit).permit(:nama, :deskripsi, :solusi)
    end

    def ceklogin
      if !user_signed_in? 
        redirect_to "/users/sign_in", notice: 'belum login'
      end
    end
  end

app/helpers/penyakits_helper.rb
module PenyakitsHelper
end

app/views/penyakits/_form.html.erb
<%= form_for(@penyakit) do |f| %>
  <% if @penyakit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@penyakit.errors.count, "error") %> prohibited this penyakit from being saved:</h2>

      <ul>
      <% @penyakit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nama %><br>
    <%= f.text_field :nama, :required => "true" %>
  </div>
  <div class="field">
    <%= f.label :deskripsi %><br>
    <%= f.text_area :deskripsi %>
  </div>
  <div class="field">
    <%= f.label :solusi %><br>
    <%= f.text_area :solusi %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/penyakits/edit.html.erb
<h1>Editing penyakit</h1>

<%= render 'form' %>

<%= link_to 'Show', @penyakit %> |
<%= link_to 'Back', penyakits_path %>

app/views/penyakits/gejala.html.erb
<h2>Macam Gejala Pada <%= @namapenyakit %></h2>

<%= form_tag("gejalaproses",:method => "post", :id => "formpesan" )  %>
<table class="table table-bordered"><tr>
<% @gejala.each do | gdata | %>
<tr><td>
 <input name="cekgejala[]" type="checkbox" value="<%= gdata._id %>" <%=  (@ar.include? gdata._id)? "checked" : "" %>> </td><td><%= gdata.nama %> </td>
 </tr>

<% end %>
</table>
    <input type='submit' class="btn btn-primary" value='Kirim'>
</form>

app/views/penyakits/gejalaproses.html.erb
<%= @data %>

app/views/penyakits/index.html.erb
<h1>Listing penyakits</h1>
<% if @er!=nil %>
<div class="alert alert-block alert-error fade in">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <h4 class="alert-heading">Terjadi Kesalahan!</h4>
            <p>Penyakit 
                <% @er.each do | data | %>
                    (<a href="/penyakits/<%= data._id %>"><%= data.nama %></a>)  
                <% end %> memiliki gejala yang sama
                <p>
            </p>
          </div>
<% end %>
<%= link_to 'New Penyakit', new_penyakit_path, :class=> "btn btn-primary" %>

<button ng-click="tableParams.sorting({})" class="btn btn-default pull-right">Clear sorting</button>
    <button ng-click="tableParams.filter({})" class="btn btn-default pull-right">Clear filter</button>
    <p><strong>Sorting:</strong> {{tableParams.sorting()|json}}
    <p><strong>Filter:</strong> {{tableParams.filter()|json}}

   <table ng-table="tableParams" show-filter="true" class="table">
        <tr ng-repeat="data in $data">
                    <td data-title="'Nama'" sortable="'nama'"  filter="{ 'nama': 'text' }">
                        {{data.nama}}
                    </td>
                    <td data-title="'Deskripsi'" sortable="'deskripsi'"  filter="{ 'deskripsi': 'text' }">
                        {{data.deskripsi}}
                    </td> 
                    <td data-title="'Aksi'" width="200">
                                              <a href="/penyakits/{{data._id.$oid}}" class="btn btn-primary">Lihat</a>
                        <a href="/penyakits/{{data._id.$oid}}/edit" class="btn btn-warning">Ubah</a>

                        <a href="/penyakits/{{data._id.$oid}}" class="btn btn-danger" data-confirm="Are you sure?" data-method="delete" rel="nofollow">Hapus</a>
                    </td> 
                </tr>
            </table>


    <script>
    
        var app = angular.module('main', ['ngTable']).
                controller('DemoCtrl', function($scope, $http,$filter, ngTableParams) {
                  
                        
                  $http.jsonp('/penyakits/jsonp?callback=JSON_CALLBACK').success(function(asd) {
                  var data = asd;
                  console.log(asd[0]._id.$oid);
                   $scope.tableParams = new ngTableParams({
                        page: 1,            // show first page
                        count: 10,          // count per page
                        filter: {
                            nama: ''       // initial filter
                        },
                        sorting: {
                            nama: 'asc'     // initial sorting
                        }
                    }, {
                        total: data.length, // length of data
                        getData: function($defer, params) {
                            // use build-in angular filter
                            var filteredData = params.filter() ?
                                    $filter('filter')(data, params.filter()) :
                                    data;
                            var orderedData = params.sorting() ?
                                    $filter('orderBy')(filteredData, params.orderBy()) :
                                    data;

                            params.total(orderedData.length); // set total for recalc pagination
                            $defer.resolve(orderedData.slice((params.page() - 1) * params.count(), params.page() * params.count()));
                        }
                    });
              });



                 
                });
                          </script>





<br>

app/views/penyakits/new.html.erb
<h1>New penyakit</h1>

<%= render 'form' %>

<%= link_to 'Back', penyakits_path %>

app/views/penyakits/show.html.erb
<p id="notice"><%= notice %></p>
<h2><%= @penyakit.nama %></h2>
<table class="table table-bordered">
<tr>
  <td> <strong>Deskripsi:</strong></td>
  <td>  <%= @penyakit.deskripsi %>
</td>
</tr><tr>
  <td> <strong>Solusi:</strong></td>
  <td>    <%= @penyakit.solusi %>

</tr><tr>
  <td> <strong>Gejala:</strong></td>
  <td>   <ul>
  <% @penyakit.gejalas.each do | data | %>
   <li><%= data.nama %></li>
  <% end %>
</ul>

</tr>
</table>
  
<%= link_to 'Edit Gejala', gejala_penyakit_path(@penyakit) %> 

</p>




<%= link_to 'Edit', edit_penyakit_path(@penyakit) %> |
<a href="/penyakits"> Back</a>