config/routes.rb
Pakar::Application.routes.draw do
  get "index/index"
  devise_for :users
  post "periksa/create"
  post "periksa/proses"
  get "periksa/index"
  get "periksa/cek"
  get "periksa/hasil"
  get 'periksa' => 'periksa#index'
  get "penyakits/jsonp"
  get "index/kerusakan"
  get "kliens/jsonp"
  get "gejalas/jsonp"

  resources :kliens
  resources :penyakits
  root "index#index"

get '/penyakits/:id/gejala', to: 'penyakits#gejala', as: 'gejala_penyakit'
post '/penyakits/:id/gejalaproses', to: 'penyakits#gejalaproses'

  resources :gejalas

  

end

app/models/klien.rb
class Klien
  include Mongoid::Document
  field :nama, type: String
  field :alamat, type: String
  field :email, type: String
  field :ip, type: String

  belongs_to :penyakit
end

app/controllers/kliens_controller.rb
class KliensController < ApplicationController
  before_action :set_klien, only: [:show, :edit, :update, :destroy]
  before_action :ceklogin
  layout "admin"

  # GET /kliens
  # GET /kliens.json
  def index
    @kliens = Klien.all
  end

  # GET /kliens/1
  # GET /kliens/1.json
  def show
  end
  def jsonp
    datak = Klien.all
    da=[]
    ar={}
    i=0

    datak.each do | data |
      da[i]={}
      da[i]=data
      da[i]['p']=''
      da[i][:p]=data.penyakit.nama
    end

    render :json => da.to_json, :callback => params[:callback]
  
  end

  # GET /kliens/new
  def new
    @klien = Klien.new
  end

  # GET /kliens/1/edit
  def edit
  end

  # POST /kliens
  # POST /kliens.json
  def create
    @klien = Klien.new(klien_params)

    respond_to do |format|
      if @klien.save
        format.html { redirect_to @klien, notice: 'Klien was successfully created.' }
        format.json { render action: 'show', status: :created, location: @klien }
      else
        format.html { render action: 'new' }
        format.json { render json: @klien.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kliens/1
  # PATCH/PUT /kliens/1.json
  def update
    respond_to do |format|
      if @klien.update(klien_params)
        format.html { redirect_to @klien, notice: 'Klien was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @klien.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kliens/1
  # DELETE /kliens/1.json
  def destroy
    @klien.destroy
    respond_to do |format|
      format.html { redirect_to kliens_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_klien
      @klien = Klien.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def klien_params
      params.require(:klien).permit(:nama, :alamat, :email, :ip)
    end
        def ceklogin
          if !user_signed_in? 
          redirect_to "/users/sign_in", notice: 'belum login'
        end
    end
end

app/helpers/kliens_helper.rb
module KliensHelper
end

app/views/kliens/_form.html.erb
<%= form_for(@klien) do |f| %>
  <% if @klien.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@klien.errors.count, "error") %> prohibited this klien from being saved:</h2>

      <ul>
      <% @klien.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nama %><br>
    <%= f.text_field :nama %>
  </div>
  <div class="field">
    <%= f.label :alamat %><br>
    <%= f.text_area :alamat %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :ip %><br>
    <%= f.text_field :ip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kliens/edit.html.erb
<h1>Editing klien</h1>

<%= render 'form' %>

<%= link_to 'Show', @klien %> |
<%= link_to 'Back', kliens_path %>

app/views/kliens/index.html.erb
<h1>Listing kliens</h1>

<button ng-click="tableParams.sorting({})" class="btn btn-default pull-right">Clear sorting</button>
    <button ng-click="tableParams.filter({})" class="btn btn-default pull-right">Clear filter</button>
    <p><strong>Sorting:</strong> {{tableParams.sorting()|json}}
    <p><strong>Filter:</strong> {{tableParams.filter()|json}}

   <table ng-table="tableParams" show-filter="true" class="table">
        <tr ng-repeat="data in $data">
                    <td data-title="'Nama'" sortable="'nama'"  filter="{ 'nama': 'text' }">
                        {{data.nama}}
                    </td>
                    <td data-title="'Alamat'" sortable="'alamat'"  filter="{ 'alamat': 'text' }">
                        {{data.alamat}}
                    </td> 
                     <td data-title="'Email'" sortable="'email'"  filter="{ 'email': 'text' }">
                        {{data.email}}
                    </td>

                    <td data-title="'Kerusakan'" sortable="'p'"  filter="{ 'p': 'text' }">
                        {{data.p}}
                    </td> 
                    <td data-title="'ip address'" sortable="'ip'"  filter="{ 'ip': 'text' }">
                        {{data.ip}}
                    </td> 
                    <td data-title="'Aksi'" width="200">
                        <a href="/kliens/{{data._id.$oid}}" class="btn btn-danger" data-confirm="Are you sure?" data-method="delete" rel="nofollow">Hapus</a>
                    </td> 
                </tr>
            </table>


    <script>
    
        var app = angular.module('main', ['ngTable']).
                controller('DemoCtrl', function($scope, $http,$filter, ngTableParams) {
                  
                        
                  $http.jsonp("<%= kliens_path %>/jsonp?callback=JSON_CALLBACK").success(function(asd) {
                  var data = asd;
                  console.log(asd[0]._id.$oid);
                   $scope.tableParams = new ngTableParams({
                        page: 1,            // show first page
                        count: 10,          // count per page
                        filter: {
                            nama: ''       // initial filter
                        },
                        sorting: {
                            nama: 'desc'     // initial sorting
                        }
                    }, {
                        total: data.length, // length of data
                        getData: function($defer, params) {
                            // use build-in angular filter
                            var filteredData = params.filter() ?
                                    $filter('filter')(data, params.filter()) :
                                    data;
                            var orderedData = params.sorting() ?
                                    $filter('orderBy')(filteredData, params.orderBy()) :
                                    data;

                            params.total(orderedData.length); // set total for recalc pagination
                            $defer.resolve(orderedData.slice((params.page() - 1) * params.count(), params.page() * params.count()));
                        }
                    });
              });



                 
                });
                          </script>





<br>

app/views/kliens/new.html.erb
<h1>New klien</h1>

<%= render 'form' %>

<%= link_to 'Back', kliens_path %>

app/views/kliens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nama:</strong>
  <%= @klien.nama %>
</p>

<p>
  <strong>Alamat:</strong>
  <%= @klien.alamat %>
</p>

<p>
  <strong>Email:</strong>
  <%= @klien.email %>
</p>

<p>
  <strong>Ip:</strong>
  <%= @klien.ip %>
</p>

<%= link_to 'Edit', edit_klien_path(@klien) %> |
<%= link_to 'Back', kliens_path %>