config/routes.rb
Pakar::Application.routes.draw do
  get "index/index"
  devise_for :users
  post "periksa/create"
  post "periksa/proses"
  get "periksa/index"
  get "periksa/cek"
  get "periksa/hasil"
  get 'periksa' => 'periksa#index'
  get "penyakits/jsonp"
  get "index/kerusakan"
  get "kliens/jsonp"
  get "gejalas/jsonp"

  resources :kliens
  resources :penyakits
  root "index#index"

get '/penyakits/:id/gejala', to: 'penyakits#gejala', as: 'gejala_penyakit'
post '/penyakits/:id/gejalaproses', to: 'penyakits#gejalaproses'

  resources :gejalas

  

end

app/models/gejala.rb
class Gejala
  include Mongoid::Document
  field :nama, type: String
  has_and_belongs_to_many  :penyakits
end

app/controllers/gejalas_controller.rb
class GejalasController < ApplicationController
  before_action :set_gejala, only: [:show, :edit, :update, :destroy]
  before_action :ceklogin
  layout "admin"

  # GET /gejalas
  # GET /gejalas.json
  def index
    
    @gejalas = Gejala.all
  end

  # GET /gejalas/1
  # GET /gejalas/1.json
def jsonp
  g=Gejala.all.to_json
  render :json => g, :callback => params[:callback]
end

  def show
  end

  # GET /gejalas/new
  def new
    @gejala = Gejala.new
  end

  # GET /gejalas/1/edit
  def edit
  end

  # POST /gejalas
  # POST /gejalas.json
  def create
    @gejala = Gejala.new(gejala_params)

    respond_to do |format|
      if @gejala.save
        format.html { redirect_to @gejala, notice: 'Gejala was successfully created.' }
        format.json { render action: 'show', status: :created, location: @gejala }
      else
        format.html { render action: 'new' }
        format.json { render json: @gejala.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gejalas/1
  # PATCH/PUT /gejalas/1.json
  def update
    respond_to do |format|
      if @gejala.update(gejala_params)
        format.html { redirect_to @gejala, notice: 'Gejala was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gejala.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gejalas/1
  # DELETE /gejalas/1.json
  def destroy
    @gejala.destroy
    respond_to do |format|
      format.html { redirect_to gejalas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gejala
      @gejala = Gejala.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gejala_params
      params.require(:gejala).permit(:nama)
    end
        def ceklogin
          if !user_signed_in? 
          redirect_to "/users/sign_in", notice: 'belum login'
        end
    end
end

app/helpers/gejalas_helper.rb
module GejalasHelper
end

app/views/gejalas/_form.html.erb
<%= form_for(@gejala) do |f| %>
  <% if @gejala.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gejala.errors.count, "error") %> prohibited this gejala from being saved:</h2>

      <ul>
      <% @gejala.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nama %><br>
    <%= f.text_field :nama, :required => "true" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gejalas/edit.html.erb
<h1>Editing gejala</h1>

<%= render 'form' %>

<%= link_to 'Show', @gejala %> |
<%= link_to 'Back', gejalas_path %>

app/views/gejalas/index.html.erb
<h1>Listing gejalas</h1>


<%= link_to 'New Gejala', new_gejala_path, :class => "btn btn-primary" %>


<button ng-click="tableParams.sorting({})" class="btn btn-default pull-right">Clear sorting</button>
    <button ng-click="tableParams.filter({})" class="btn btn-default pull-right">Clear filter</button>
    <p><strong>Sorting:</strong> {{tableParams.sorting()|json}}
    <p><strong>Filter:</strong> {{tableParams.filter()|json}}

   <table ng-table="tableParams" show-filter="true" class="table">
        <tr ng-repeat="data in $data">
                    <td data-title="'Nama'" sortable="'nama'"  filter="{ 'nama': 'text' }">
                        {{data.nama}}
                    </td>
                    <td data-title="'Aksi'" width="200">
                                              <a href="/gejalas/{{data._id.$oid}}" class="btn btn-primary">Lihat</a>
                        <a href="/gejalas/{{data._id.$oid}}/edit" class="btn btn-warning">Ubah</a>

                        <a href="/gejalas/{{data._id.$oid}}" class="btn btn-danger" data-confirm="Are you sure?" data-method="delete" rel="nofollow">Hapus</a>
                    </td> 
                </tr>
            </table>


    <script>
    
        var app = angular.module('main', ['ngTable']).
                controller('DemoCtrl', function($scope, $http,$filter, ngTableParams) {
                  
                        
                  $http.jsonp('/gejalas/jsonp?callback=JSON_CALLBACK').success(function(asd) {
                  var data = asd;
                  console.log(asd[0]._id.$oid);
                   $scope.tableParams = new ngTableParams({
                        page: 1,            // show first page
                        count: 10,          // count per page
                        filter: {
                            nama: ''       // initial filter
                        },
                        sorting: {
                            nama: 'desc'     // initial sorting
                        }
                    }, {
                        total: data.length, // length of data
                        getData: function($defer, params) {
                            // use build-in angular filter
                            var filteredData = params.filter() ?
                                    $filter('filter')(data, params.filter()) :
                                    data;
                            var orderedData = params.sorting() ?
                                    $filter('orderBy')(filteredData, params.orderBy()) :
                                    data;

                            params.total(orderedData.length); // set total for recalc pagination
                            $defer.resolve(orderedData.slice((params.page() - 1) * params.count(), params.page() * params.count()));
                        }
                    });
              });



                 
                });
                          </script>





<br>

app/views/gejalas/new.html.erb
<h1>New gejala</h1>

<%= render 'form' %>

<%= link_to 'Back', gejalas_path %>

app/views/gejalas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nama:</strong>
  <%= @gejala.nama %>
</p>

<%= link_to 'Edit', edit_gejala_path(@gejala) %> |
<%= link_to 'Back', gejalas_path %>