config/routes.rb
Pakar::Application.routes.draw do
  get "index/index"
  devise_for :users
  post "periksa/create"
  post "periksa/proses"
  get "periksa/index"
  get "periksa/cek"
  get "periksa/hasil"
  get 'periksa' => 'periksa#index'
  get "penyakits/jsonp"
  get "index/kerusakan"
  get "kliens/jsonp"
  get "gejalas/jsonp"

  resources :kliens
  resources :penyakits
  root "index#index"

get '/penyakits/:id/gejala', to: 'penyakits#gejala', as: 'gejala_penyakit'
post '/penyakits/:id/gejalaproses', to: 'penyakits#gejalaproses'

  resources :gejalas

  

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pakar</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "ng-table" %>
  <%= javascript_include_tag 'angular.min' %>
  <%= javascript_include_tag 'ng-table' %>


  <%= csrf_meta_tags %>

</head>
<body ng-app="main">
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="/">Sistem Pakar</a>
          <div class="nav-collapse collapse">
            <p class="navbar-text pull-right">
              Logged in as <%= current_user.email %> | <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>

            </p>

<ul class="nav">
  <li class="<%= 'active' if current_page?(penyakits_path) %>"><%= link_to "Penyakit", penyakits_path %></li>
  <li class="<%= 'active' if current_page?(gejalas_path) %>"><%= link_to "Gejala", gejalas_path %></li>
  <li class="<%= 'active' if current_page?(kliens_path) %>"><%= link_to "Klien", kliens_path %></li>

            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

 <div class="container" ng-controller="DemoCtrl">

<%= yield %>
    </div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pakar</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="/">Pakar Komputer</a>
          <div class="nav-collapse collapse">
                      
<% if user_signed_in? %>
<ul class="nav pull-right">  
       <li class="dropdown">  
         <a class="dropdown-toggle" data-toggle="dropdown" href="#">Logged in as <%= current_user.email %><b class="caret"></b></a>  
         <ul class="dropdown-menu">  
           <li><%= link_to "Admin Area", penyakits_path %></li> 
                      <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>   
         </ul>  
       </li>  
     </ul> 
               
              <% else %>
                          <p class="navbar-text pull-right">

              <%=  link_to "Sign in", new_user_session_path %>
                                        </p>

            <% end %>
            <ul class="nav">
              <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
  <li class="<%= 'active' if current_page?(periksa_index_path) %>"><%= link_to "Periksa Kerusakan", periksa_index_path %></li>
  <li class="<%= 'active' if current_page?(index_kerusakan_path) %>"><%= link_to "Daftar Kerusakan", index_kerusakan_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

 <div class="container well">
 <div id="myCarousel" class="carousel slide">
                <ol class="carousel-indicators">
                  <li data-target="#myCarousel"></li>
                </ol>
                <div class="carousel-inner">
                    <img src="/img/h.jpg" alt="">
                    <div class="carousel-caption">
                      <h4>Sistem Pakar Kerusakan Komputer</h4>
                      <p>Sistem pakar adalah suatu program komputer yang mengandung pengetahuan dari satu atau lebih pakar manusia mengenai suatu bidang spesifik.</p>
                    </div>
                  </div>
              </div>
<%= yield %>
    </div>

</body>

<footer class="container" align="right">
System Pakar 2014
</footer>
</html>